### ISSUE TITLE
[SUG-25] Sweep: Add a trie data structure containing each file in the vault

### ISSUE THREAD

**Issue by connerohnesorge** [connerohnesorge/sugar-rushh#15]
Add a trie.ts file in src that is indexed when the plugin loads containing a trie data structure containing files and folders within the obsidian vault that the plugin is used within

<sub>[SUG-25](https://linear.app/sugar-obsidian/issue/SUG-25/sweep-add-a-trie-data-structure-containing-each-file-in-the-vault)</sub>

<details open>
<summary>Checklist</summary>

- [X] Create `src/trie.ts` ✓ https://github.com/conneroisu/sugar-rush/commit/61d32c3247972a21c7465a1c6603da8aa604627a
- [X] Modify `src/main.ts` ✓ https://github.com/conneroisu/sugar-rush/commit/e3f6889b7947ae47c797a0e22aa0e1f1f6c7364f

![Flowchart](https://raw.githubusercontent.com/conneroisu/sugar-rush/sweep/assets/60fe91269141bbd35869aa6cba745e800ec92c3e4585650ae45d0c78077aae2c_15_flowchart.svg)
</details>

**Comment by ghost** [comment]
## Here's the PR! [https://github.com/conneroisu/sugar-rush/pull/17](https://github.com/conneroisu/sugar-rush/pull/17).
<div align='center'>💎 <b>Sweep Pro</b>: I'm using GPT-4. You have unlimited GPT-4 tickets. (tracking ID: <code>abc1987a2c</code>)</div>

---
## Actions (click)
- [ ] ↻ Restart Sweep

## Sandbox execution failed

The sandbox appears to be unavailable or down.


<div align='center'>Install Sweep Configs: <a href='https://github.com/conneroisu/sugar-rush/pull/16'>Pull Request</a></div>

---
## Step 1: 🔎 Searching
I found the following snippets in your repository. I will now analyze these snippets and come up with a plan.


<details >
<summary>Some code snippets I looked at (click to expand). If some file is missing from here, you can mention the path in the ticket description.</summary>

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/README.md#L30-L45

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/src/main.ts#L1-L49

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/src/utils/OpenEntry.ts#L1-L11

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/README.md#L45-L60

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/README.md#L15-L30

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/src/utils/OpenSugarFile.ts#L1-L22

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/manifest.json#L1-L10

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/src/settings/SettingsPage.ts#L1-L29

https://github.com/conneroisu/sugar-rush/blob/de0f61b7a517865e237b185840c33c5f9668e622/src/settings/PluginSettings.ts#L1-L2

</details>

<details >
<summary>I also found the following external resources that might be helpful:</summary>





**Summaries of links found in the content:**

https://linear.app/sugar-obsidian/issue/SUG-25/sweep-add-a-trie-data-structure-containing-each-file-in-the-vault)</sub:

I'm sorry, but it seems that the page content provided is not accessible or relevant to the problem you are trying to solve. If you have access to the content of the page or any specific details related to the problem, please provide them, and I would be happy to help you with a summary.





</details>


---
## Step 2: ⌨️ Coding
- [X] Create `src/trie.ts` ✓ https://github.com/conneroisu/sugar-rush/commit/61d32c3247972a21c7465a1c6603da8aa604627a
<blockquote>Create src/trie.ts with contents:<br/>• Create a new file `trie.ts` in the `src` directory.<br/>• In `trie.ts`, import the `App` class from Obsidian.<br/>• Implement the Trie data structure in `trie.ts`. The Trie should be able to store and retrieve file and folder paths.<br/>• Create a function `populateTrie` that takes an instance of `App` as an argument. This function should get the list of all files and folders in the vault using the `App.vault.getFiles()` and `App.vault.getFolders()` methods, and add them to the Trie.<br/>• Export the `populateTrie` function from `trie.ts`.
</blockquote>

- [X] Modify `src/main.ts` ✓ https://github.com/conneroisu/sugar-rush/commit/e3f6889b7947ae47c797a0e22aa0e1f1f6c7364f
<blockquote>Modify src/main.ts with contents:<br/>• Import the `populateTrie` function from `trie.ts` at the top of `main.ts`.<br/>• In the `onload` method of the `SugarRushPlugin` class in `main.ts`, call the `populateTrie` function, passing `this.app` as the argument. This will ensure that the Trie is populated with all files and folders in the vault when the plugin loads.
</blockquote>


---
## Step 3: 🔁 Code Review
I have finished reviewing the code for completeness. I did not find errors for  [`sweep/trie-vault-indexing`](https://github.com/conneroisu/sugar-rush/commits/sweep/trie-vault-indexing).



---

### 🎉 Latest improvements to Sweep:

* Sweep now uses the `rope` library to refactor Python! Check out [Large Language Models are Bad at Refactoring Code](https://docs.sweep.dev/blogs/refactor-python). To have Sweep refactor your code, try `sweep: Refactor <your_file>.py`!
* Sweep finds and fixes bugs in your code by writing unit tests! Check out [Having GPT-4 Iterate on Unit Tests like a Human](https://docs.sweep.dev/blogs/ai-unit-tests).


---
 💡 To recreate the pull request edit the issue title or description. To tweak the pull request, leave a comment on the pull request.
<sup>[Join Our Discord](https://discord.com/invite/sweep)
